sudo: required
language: generic

before_install:
  - echo $LANG
  - echo $LC_ALL
  - echo $USER

script:
  - ./travis-build/build.sh

before_deploy:
  - export RELEASE_FILES=$(ls *.changes *.dsc *.orig.tar.* *.debian.tar.* *.deb *.buildinfo)
  - ls -la
  - echo "Deploying $RELEASE_PKG_FILE to GitHub releases"

deploy:
  provider: releases
  api_key:
    secure:
  file: "${RELEASE_PKG_FILE}"
  on:
    tags: true
