sudo: required
language: generic

env:
  - DIST=stable TARGET_DIST=stretch-backports

before_install:
  - echo $LANG
  - echo $LC_ALL
  - echo $USER
  - echo $DIST

script:
  - git fetch origin pristine-tar:pristine-tar
  - ./travis-build/build.sh $DIST $TARGET_DIST

deploy:
  provider: script
  script: ./travis-build/deploy.sh streamlink-debian $DIST $TARGET_DIST
  skip_cleanup: true
  on:
    tags: true
