sudo: required
language: generic

before_install:
  - echo $LANG
  - echo $LC_ALL
  - echo $USER

script:
  - ./travis-build/build.sh

before_deploy:
  - export RELEASE_FILES=$(ls *.dsc *.deb *.tar.xz *.orig.tar.gz *.changes)
  - echo "Deploying $RELEASE_PKG_FILE to GitHub releases"

deploy:
  provider: releases
  api_key:
    secure:
  file: "${RELEASE_PKG_FILE}"
  on:
    tags: true
