
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-24T17:53:39-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "6a30ed7524eff2cdb205e024294b187cb660e4e3",
 "version": "2.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
