
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-30T17:18:36-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f7ac8947b80822c5cbfbf9d6f13e314e53865507",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
