# This is a basic workflow to help you get started with Actions

name: "Check upstream"

# Controls when the workflow will run
on:
  # Schedule every days at 18:00 UTC
  schedule:
    - cron: "0 18 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install uscan
      - name: Install uscan
        run: |
          sudo apt-get update
          sudo apt-get install devscripts

      # Runs a single command using the runners shell
      - name: Check upstream
        run: ./check-upstream.sh
